### ISSUE TITLE
Issue with importing pymer4: "stats" package not found

### ISSUE THREAD

**Issue by rafamestre** [ejolly/pymer4#101]
Hi,

I'm having problems loading the pymer4 package after installation. I've done it with Anaconda and following the instructions, in different environments. I've tried with the four ways of installing according to these guidelines, but none of them work. To test it, I've tried to load the package in python or writing in the command line `python -c "from pymer4.test_install import test_install; test_install()"` to test like it says in the installation help. The error that I got initially when installing myself was number 2 below, but the different ways of installing throw different errors.

1. `conda create --name test_env1 -c ejolly -c defaults -c conda-forge pymer4`

```
(test_env1) C:\Users\rmc1r21>python -c "from pymer4.test_install import test_install; test_install()"
Error in glue(.Internal(R.home()), "library", "base", "R", "base", sep = .Platform$file.sep) :
  4 arguments passed to .Internal(paste) which requires 3
Error: could not find function "attach"
Error: could not find function "options"
Error: object '.ArgsEnv' not found

```

2. `conda create --name test_env2 -c ejolly -c conda-forge -c defaults pymer4`

```
(test_env2) C:\Users\rmc1r21>python -c "from pymer4.test_install import test_install; test_install()"
During startup - Warning message:
package 'stats' in options("defaultPackages") was not found
R[write to console]: Error: package or namespace load failed for 'stats' in inDL(x, as.logical(local), as.logical(now), ...):
 unable to load shared object 'C:/Program Files/R/R-4.1.2/library/stats/libs/x64/stats.dll':
  LoadLibrary failure:  The specified module could not be found.


R[write to console]: Error in inDL(x, as.logical(local), as.logical(now), ...) :
  unable to load shared object 'C:/Program Files/R/R-4.1.2/library/stats/libs/x64/stats.dll':
  LoadLibrary failure:  The specified module could not be found.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\rmc1r21\Anaconda3\envs\test_env2\lib\site-packages\pymer4\__init__.py", line 5, in <module>
    from .models import Lmer, Lm, Lm2
  File "C:\Users\rmc1r21\Anaconda3\envs\test_env2\lib\site-packages\pymer4\models\__init__.py", line 5, in <module>
    from .Lmer import Lmer
  File "C:\Users\rmc1r21\Anaconda3\envs\test_env2\lib\site-packages\pymer4\models\Lmer.py", line 33, in <module>
    stats = importr("stats")
  File "C:\Users\rmc1r21\Anaconda3\envs\test_env2\lib\site-packages\rpy2\robjects\packages.py", line 484, in importr
    env = _get_namespace(name)
  File "C:\Users\rmc1r21\Anaconda3\envs\test_env2\lib\site-packages\rpy2\rinterface_lib\conversion.py", line 45, in _
    cdata = function(*args, **kwargs)
  File "C:\Users\rmc1r21\Anaconda3\envs\test_env2\lib\site-packages\rpy2\rinterface.py", line 680, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in inDL(x, as.logical(local), as.logical(now), ...) :
  unable to load shared object 'C:/Program Files/R/R-4.1.2/library/stats/libs/x64/stats.dll':
  LoadLibrary failure:  The specified module could not be found.

```

I have checked and the stats library is in that path. I've also installed Rstudio and I could open it without problems.

3. `conda create --name test_env3 -c ejolly/label/pre-release -c defaults -c conda-forge pymer4`

```
(test_env3) C:\Users\rmc1r21>python -c "from pymer4.test_install import test_install; test_install()"
Error in glue(.Internal(R.home()), "library", "base", "R", "base", sep = .Platform$file.sep) :
  4 arguments passed to .Internal(paste) which requires 3
Error: could not find function "attach"
Error: could not find function "options"
Error: object '.ArgsEnv' not found

```

Here, a pop-up appears saying: Fatal error: unable to initialize the JIT.

4. `conda create --name test_env4 -c ejolly/label/pre-release -c conda-forge -c defaults pymer4`

With this one I get loads of errors when installing, they look something like:

```
CondaVerificationError: The package for m2w64-gsl located at C:\Users\rmc1r21\Anaconda3\pkgs\m2w64-gsl-2.1-2
appears to be corrupted. The path 'Library/mingw-w64/share/man/man3/gsl.3.gz'
specified in the package manifest cannot be found.
```
With a different package each time.

I'm attaching the pymer4_issue.txt file here:

[pymer4_issue.txt](https://github.com/ejolly/pymer4/files/8235235/pymer4_issue.txt)

This is my system information:

```
Host Name:                 UOS-019445
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19042 N/A Build 19042
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Product ID:                00329-00000-00003-AA649
Original Install Date:     12/03/2021, 09:03:12
System Boot Time:          11/03/2022, 19:47:09
System Manufacturer:       Dell Inc.
System Model:              Latitude 5410
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 142 Stepping 12 GenuineIntel ~1609 Mhz
BIOS Version:              Dell Inc. 1.3.2, 23/09/2020
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             en-gb;English (United Kingdom)
Input Locale:              en-gb;English (United Kingdom)
Time Zone:                 (UTC+00:00) Dublin, Edinburgh, Lisbon, London
Total Physical Memory:     16,012 MB
Available Physical Memory: 6,285 MB
Virtual Memory: Max Size:  36,492 MB
Virtual Memory: Available: 25,849 MB
Virtual Memory: In Use:    10,643 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    soton.ac.uk
Logon Server:              \\SRV03255
Hotfix(s):                 12 Hotfix(s) Installed.
                           [01]: KB5009467
                           [02]: KB4562830
                           [03]: KB4570334
                           [04]: KB4577266
                           [05]: KB4580325
                           [06]: KB4593175
                           [07]: KB4598481
                           [08]: KB5010342
                           [09]: KB5006753
                           [10]: KB5007273
                           [11]: KB5011352
                           [12]: KB5005699
Network Card(s):           2 NIC(s) Installed.
                           [01]: Intel(R) Ethernet Connection (10) I219-V
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [02]: Intel(R) Wi-Fi 6 AX201 160MHz
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.1
                                 IP address(es)
                                 [01]: 192.168.1.16
                                 [02]: fe80::7844:775d:1bc:c1b5
                                 [03]: fdaa:bbcc:ddee:0:f581:7db0:4400:b01f
                                 [04]: 2a0e:cb01:16:7f00:f581:7db0:4400:b01f
                                 [05]: fdaa:bbcc:ddee:0:7844:775d:1bc:c1b5
                                 [06]: 2a0e:cb01:16:7f00:b887:4a1a:ed4a:65a8
                                 [07]: 2a0e:cb01:16:7f00:7844:775d:1bc:c1b5
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

```

Thanks a lot for the help!

**Comment by ejolly** [comment]
@rafamestre Hmm so I think what be happening here is what others experienced in #100 . If some other program, config file, etc, is setting your `R_HOME` environment variable that's usually when issues like this arise. Unfortunately it's not easy for me to manually debug because I don't have access to a windows machine, so you want to try the proposed solution in #100 ?

**Comment by ejolly** [comment]
@rafamestre I just created a new release that pins the `rpy2` version to 3.4.5 as the newer versions seem to be causing an issue. Can you try with the latest release of pymer4? I'm going to close this issue in the mean time, but feel free to reopen
