### ISSUE TITLE
nbinom

### ISSUE THREAD

**Issue by mabaoweireadingene** [ejolly/pymer4#138]
model = Lmer("DV_l ~ IV3 + (IV3|Group)", data=df,family='nbinom')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/share/TJPROJ5/public/softwares/conda/miniforge3_20240402/envs/scanpy_20240215/lib/python3.12/site-packages/pymer4/models/Lmer.py", line 84, in __init__
    raise ValueError(
ValueError: Family must be one of: gaussian, binomial, gamma, inverse_gaussian or poisson!
 could it used for nbinom？？

**Comment by ejolly** [comment]
I don't think that's an officially supported family from the R docs so it's unlikely I could support it: https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/family

I don't have complete coverage of all possible families, but if there's a particular use case I'm happy to take PRs!
