### ISSUE TITLE
can't find dll

### ISSUE THREAD

**Issue by MarkAPitt** [ejolly/pymer4#14]
Windows 7 running Anaconda, python 2.7, 32-bit with Spyder IDE. All packages satisfy the requirements.
The DLL is in the distribution's path.

Any suggestions would be appreciated. Thanks.

from pymer4.models import Lmer
Traceback (most recent call last):

  File "<ipython-input-1-ae302b076a61>", line 1, in <module>
    from pymer4.models import Lmer

  File "C:\Program Files (x86)\Anaconda2\Lib\site-packages\pymer4\__init__.py", line 2, in <module>
    from models import Lmer

  File "C:\Program Files (x86)\Anaconda2\Lib\site-packages\pymer4\models.py", line 1, in <module>
    import rpy2.robjects as robjects

  File "C:\Program Files (x86)\Anaconda2\Lib\site-packages\rpy2\robjects\__init__.py", line 16, in <module>
    import rpy2.rinterface as rinterface

  File "C:\Program Files (x86)\Anaconda2\Lib\site-packages\rpy2\rinterface\__init__.py", line 87, in <module>
    _load_r_dll(R_HOME)

  File "C:\Program Files (x86)\Anaconda2\Lib\site-packages\rpy2\rinterface\__init__.py", line 64, in _load_r_dll
    ctypes.CDLL(r_dll)

  File "C:\Program Files (x86)\Anaconda2\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)

WindowsError: [Error 126] The specified module could not be found

![image](https://user-images.githubusercontent.com/7736211/30292228-5c83642e-9703-11e7-99db-c3613b4e1982.png)

**Comment by ejolly** [comment]
Sorry I just saw this. Hmm it looks like a problem with Anaconda's handling of c-type initialization? Are you able to use other c-dependent python packages in your anaconda install (e.g numpy?) 

Unfortunately I don't have easy access to a Windows machine to test this on, but I know other Windows users haven't run into this particular issue.

**Comment by ejolly** [comment]
Going to close this for now as it's unclear whether this is a general installation problem or user-specific. Will re-open if others have the same problem
