### ISSUE TITLE
installation issue for pymer4

### ISSUE THREAD

**Issue by jagadavk** [ejolly/pymer4#38]
base) C:\Users\j.siddaramanna>conda install pymer4
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - pymer4

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

(base) C:\Users\j.siddaramanna>pip install pymer4
Collecting pymer4
  Using cached https://files.pythonhosted.org/packages/fe/81/a5a639614c22b901905418f1f7f5364ae23c97ae4b081904665308ff233a/pymer4-0.6.0-py2.py3-none-any.whl
Requirement already satisfied: patsy>=0.4.1 in c:\users\j.siddaramanna\appdata\local\continuum\anaconda3\lib\site-packages (from pymer4) (0.5.1)
Requirement already satisfied: pandas>=0.19.1 in c:\users\j.siddaramanna\appdata\local\continuum\anaconda3\lib\site-packages (from pymer4) (0.23.4)
Requirement already satisfied: matplotlib>=2.0 in c:\users\j.siddaramanna\appdata\local\continuum\anaconda3\lib\site-packages (from pymer4) (3.0.2)
Collecting rpy2>=2.9.4 (from pymer4)
  Using cached https://files.pythonhosted.org/packages/9c/81/86f9ba26b4fb27c17a143c064301f4928681c96c09c59edb23a44767c3d6/rpy2-3.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "c:\users\j.siddaramanna\appdata\local\continuum\anaconda3\lib\site-packages\cffi\cparser.py", line 276, in _parse
        ast = _get_parser().parse(fullcsource)
      File "c:\users\j.siddaramanna\appdata\local\continuum\anaconda3\lib\site-packages\pycparser\c_parser.py", line 152, in parse
        debug=debuglevel)
      File "c:\users\j.siddaramanna\appdata\local\continuum\anaconda3\lib\site-packages\pycparser\ply\yacc.py", line 331, in parse
        return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
      File "c:\users\j.siddaramanna\appdata\local\continuum\anaconda3\lib\site-packages\pycparser\ply\yacc.py", line 1199, in parseopt_notrack
        tok = call_errorfunc(self.errorfunc, errtoken, self)
      File "c:\users\j.siddaramanna\appdata\local\continuum\anaconda3\lib\site-packages\pycparser\ply\yacc.py", line 193, in call_errorfunc
        r = errorfunc(token)
      File "c:\users\j.siddaramanna\appdata\local\continuum\anaconda3\lib\site-packages\pycparser\c_parser.py", line 1848, in p_error
        column=self.clex.find_tok_column(p)))
      File "c:\users\j.siddaramanna\appdata\local\continuum\anaconda3\lib\site-packages\pycparser\plyparser.py", line 67, in _parse_error
        raise ParseError("%s: %s" % (coord, msg))
    pycparser.plyparser.ParseError: <cdef source string>:23:5: before: blah1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\JA6F5~1.SID\AppData\Local\Temp\pip-install-sj6qv50w\rpy2\setup.py", line 185, in <module>
        'rpy2': ['doc/source/rpy2_logo.png', ]}
      File "c:\users\j.siddaramanna\appdata\local\continuum\anaconda3\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\j.siddaramanna\appdata\local\continuum\anaconda3\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\users\j.siddaramanna\appdata\local\continuum\anaconda3\lib\site-packages\setuptools\dist.py", line 447, in __init__
        k: v for k, v in attrs.items()
      File "c:\users\j.siddaramanna\appdata\local\continuum\anaconda3\lib\distutils\dist.py", line 292, in __init__
        self.finalize_options()
      File "c:\users\j.siddaramanna\appdata\local\continuum\anaconda3\lib\site-packages\setuptools\dist.py", line 739, in finalize_options
        ep.load()(self, ep.name, value)
      File "c:\users\j.siddaramanna\appdata\local\continuum\anaconda3\lib\site-packages\cffi\setuptools_ext.py", line 204, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "c:\users\j.siddaramanna\appdata\local\continuum\anaconda3\lib\site-packages\cffi\setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "c:\users\j.siddaramanna\appdata\local\continuum\anaconda3\lib\site-packages\cffi\setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "rpy/_rinterface_cffi_build.py", line 546, in <module>
        """ if os.name == 'nt' else ''
      File "c:\users\j.siddaramanna\appdata\local\continuum\anaconda3\lib\site-packages\cffi\api.py", line 107, in cdef
        self._cdef(csource, override=override, packed=packed)
      File "c:\users\j.siddaramanna\appdata\local\continuum\anaconda3\lib\site-packages\cffi\api.py", line 121, in _cdef
        self._parser.parse(csource, override=override, **options)
      File "c:\users\j.siddaramanna\appdata\local\continuum\anaconda3\lib\site-packages\cffi\cparser.py", line 315, in parse
        self._internal_parse(csource)
      File "c:\users\j.siddaramanna\appdata\local\continuum\anaconda3\lib\site-packages\cffi\cparser.py", line 320, in _internal_parse
        ast, macros, csource = self._parse(csource)
      File "c:\users\j.siddaramanna\appdata\local\continuum\anaconda3\lib\site-packages\cffi\cparser.py", line 278, in _parse
        self.convert_pycparser_error(e, csource)
      File "c:\users\j.siddaramanna\appdata\local\continuum\anaconda3\lib\site-packages\cffi\cparser.py", line 307, in convert_pycparser_error
        raise CDefError(msg)
    cffi.error.CDefError: cannot parse "blah1 ReadConsole;"
    <cdef source string>:23:5: before: blah1

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\JA6F5~1.SID\AppData\Local\Temp\pip-install-sj6qv50w\rpy2\

**Comment by james-morrison-mowi** [comment]
See #33.

If you call:
conda install rpy2=2.9.4

then:

pip install pymer4

It should install without out the above error.

**Comment by ejolly** [comment]
@jagadavk sorry for being so late to get to this, but please try with the latest release of pymer4. Lots of bug fixes and compatibility issues solved in that version

@james-morrison-mowi Thanks for addressing this and providing support!

**Comment by moritz-gerster** [comment]
I get the same error 

> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - pymer4
> 
> Current channels:
> 
>   - https://conda.anaconda.org/ejolly/label/pre-release/osx-arm64
>   - https://conda.anaconda.org/ejolly/label/pre-release/noarch
>   - https://conda.anaconda.org/conda-forge/osx-arm64
>   - https://conda.anaconda.org/conda-forge/noarch
>   - https://repo.anaconda.com/pkgs/main/osx-arm64
>   - https://repo.anaconda.com/pkgs/main/noarch
>   - https://repo.anaconda.com/pkgs/r/osx-arm64
>   - https://repo.anaconda.com/pkgs/r/noarch
> 
> To search for alternate channels that may provide the conda package you're
> looking for, navigate to
> 
>     https://anaconda.org
> 
> and use the search bar at the top of the page.

I have tried all these commands:

`conda install -c ejolly/label/pre-release -c conda-forge -c defaults pymer4
`
` conda install -c ejolly -c conda-forge -c defaults pymer4
`
`conda install -c "ejolly/label/pre-release" pymer4 
`
` conda install -c ejolly pymer4  
`
` conda install pymer4  
`
`conda install -c ejolly -c defaults  pymer4    
`

**Comment by ejolly** [comment]
Hmm you're likely running into this because I've never made no-arch or arm64 builds of pymer as I don't have access to an m1 for building. I can try to make a no-arch build but won't have time until the end of this month or next month. 

You can try pip in the mean time if you can get all the other dependencies working, but it's a bit tricky with the required R packages which conda handles well. If you do get a pip only install working it would be very helpful if you could share your steps!

**Comment by moritz-gerster** [comment]
Alright, thanks for the feedback! I'll check how I'll proceed

**Comment by ejolly** [comment]
Hi @moritz-gerster I've finally had time to circle back to this and version 0.8.1 includes a `no-arch` build of pymer4 that's installable and working on m1/m2 macs. Feel free to try that out!

**Comment by moritz-gerster** [comment]
Now it works, thank you @ejolly!
