### ISSUE TITLE
Update docs to "best" install command

### ISSUE THREAD

**Issue by ejolly** [ejolly/pymer4#77]
An unusual bug when installing on macOS (and maybe some linux distros) using the command currently listed on the docs site, is that conda will not properly link to `@rpath/R/lib/libRlapack.dylib`. This means pymer4 fails to run because of dependency resolution error in the `Matrix` package:

```
# Installs Pyhon = 3.8.3 as of the time of this writing
conda create --name pymer4 -c ejolly -c defaults -c conda-forge pymer4 
conda activate pymer4
python -c "from pymer4.test_install import test_install; test_install()"

# Fails with the following:

Error! Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/Users/USER/anaconda3/envs/pymer4/lib/R/library/Matrix/libs/Matrix.dylib':
  dlopen(/Users/USER/anaconda3/envs/pymer4/lib/R/library/Matrix/libs/Matrix.dylib, 6): Library not loaded: @rpath/R/lib/libRlapack.dylib
  Referenced from: /Users/USER/anaconda3/envs/pymer4/lib/R/library/Matrix/libs/Matrix.dylib
  Reason: image not found
```

This doesn't seem to be specific to `pymer4` because opening a new R REPL session from within a new environment with `pymer4` installed produces the same error:

```
conda create --name pymer4 -c ejolly -c defaults -c conda-forge pymer4
conda activate pymer4
R
# We're now within the R REPL

library(Matrix)

# Fails with the following

Error: package or namespace load failed for ‘Matrix’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/USER/anaconda3/envs/pymer4/lib/R/library/Matrix/libs/Matrix.dylib':
  dlopen(/Users/USER/anaconda3/envs/pymer4/lib/R/library/Matrix/libs/Matrix.dylib, 6): Library not loaded: @rpath/R/lib/libRlapack.dylib
  Referenced from: /Users/USER/anaconda3/envs/pymer4/lib/R/library/Matrix/libs/Matrix.dylib
  Reason: image not found

```

At least 2 solutions to this seem to be:

1) Prioritize/prefer conda-forge over base (also works if you completely drop the defaults channel):

`conda create --name pymer4_cf -c ejolly -c conda-forge -c defaults pymer4`
This installs Python = 3.8.6 and `pymer4` works, but now most of our packages are coming from conda-forge which might screw things up for users who install additional packages into this environment that don't come from conda-forge

2) Request a specific python version (3.7 and 3.8 both work) when installing:

`conda create --name pymer4_3.6 pymer4 -c ejolly -c defaults -c conda-forge`
Installs Python = 3.6.12 and `pymer4` works 

`conda create --name pymer4_3.7 pymer4 -c ejolly -c defaults -c conda-forge`
Installs Python = 3.7.9 and `pymer4` works 

`conda create --name pymer4_3.8 pymer4 -c ejolly -c defaults -c conda-forge`
Installs Python = 3.8.5 and `pymer4` works

**Comment by turbach** [comment]
I can't replicate the problem but there are at least two things going on here. One is the new conda update 4.9 seems to be  buggy, the other is your OSX and mine behave differently, reasons unknown.

The first issue looks like teething problems when the conda installer jumped from 4.8 to 4.9 a couple weeks ago. Lots of bug reports in issues and already a patch release 4.9.1 about 4 days ago https://anaconda.org/anaconda/conda/files. And I started getting new and unwanted behavior where package installs in an existing environment tried to replace the installed mkl blas with openblas. So it feels like the conda installer update is working out kinks and I'm not yet overly concerned.

As for your specific missing lapack problem in R I couldn't replicate it on our CentOS 7 linux and Travis says Ubuntu is OK so I thought maybe its an OSX issue.

But I can't can't replicate it on OSX either which is a bit odd.

For me the default install works fine but the install with the explicit python version 3.8 fails badly. The same explicit install works fine on conda 4.8.5, so I figure conda 4.9.1 is buggy.

The following is all on OSX 10.15.7 with conda 4.9.1 in a bash shell.

Here's what I get for the default install ... smooth install, pytests pass.

`conda create --name test_pymer4 -c ejolly -c defaults -c conda-forge pymer4 -y `

```
(test_pymer4) tpumbp3:pymer4_test2 turbach$ conda --version
conda 4.9.1
(test_pymer4) tpumbp3:pymer4_test2 turbach$ git log -n 1
commit 96ac77dd548d6e0229f803ac754b3d302b4fd7a6 (HEAD -> dev, origin/dev)
Author: ejolly <eshin.jolly@gmail.com>
Date:   Wed Oct 21 23:10:21 2020 -0400

    Fix minor formatting
(test_pymer4) tpumbp3:pymer4 turbach$ conda list | egrep "(pymer4|python|blas|lapack|r-base|r-matrix|r-lme4|rpy2)"
# packages in environment at /Users/turbach/miniconda3/envs/test_pymer4:
blas                      1.0                         mkl
pymer4                    0.7.1            py38r7e98fa2_0    ejolly
python                    3.8.2                hfe9666f_0
python-dateutil           2.8.1                      py_0
python_abi                3.8                      1_cp38    conda-forge
r-base                    3.6.1                hcb44179_1
r-lme4                    1.1_21            r36h466af19_0
r-matrix                  1.2_17            r36h46e59ec_0
rpy2                      3.3.6           py38r36h174b24a_0    conda-forge
(test_pymer4) tpumbp3:pymer4 turbach$ pytest
===========================================================================================
test session starts
===========================================================================================
platform darwin -- Python 3.8.2, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: /Users/turbach/Work/testing/pymer4_test2collected 31 items                                                                                                                                                                                        
test_install.py .                                                                                                                                                                                   [  3%]
tests/test_models.py .......................                                                                                                                                                        [ 77%]
tests/test_simulate.py ..                                                                                                                                                                           [ 83%]
tests/test_stats.py ....                                                                                                                                                                            [ 96%]
tests/test_utils.py .                                                                                                                                                                               [100%]

============================================================================================
warnings summary
=============================================================================================
../../../../miniconda3/envs/test_pymer4/lib/python3.8/site-packages/patsy/constraint.py:13 /Users/turbach/miniconda3/envs/test_pymer4/lib/python3.8/site-packages/patsy/constraint.py:13: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working    from collections import Mapping
-- Docs: https://docs.pytest.org/en/stable/warnings.html
================================================================================
31 passed, 1 warning in 94.84s (0:01:34)
=================================================================================

```

Note this installs the R packages from -c r,  there is no top-level conda lapack, but the R subsystem has it and can find it so pymer4 tests OK.

```
/Users/turbach/miniconda3/envs/test_pymer4
(test_pymer4) tpumbp3:test_pymer4 turbach$ find . -name "*lapack*.dylib"
./lib/R/lib/libRlapack.dylib
./lib/R/modules/lapack.dylib
./lib/libmkl_scalapack_ilp64.dylib
./lib/libmkl_scalapack_lp64.dylib

```

However, when I try the explicit python 3.8 installation the conda dependency solver screws up the R install badly and makes an unusable environment ... missing dependencies. And its not simply one bad package build with a missing lapack dependency.

`conda create --name pymer4_3.8 pymer4 -c ejolly -c defaults -c conda-forge`

```
(base) tpumbp3:pymer4 turbach$ conda activate test_pymer4_3.8
(test_pymer4_3.8) tpumbp3:pymer4 turbach$ conda list | egrep "(pymer4|python|blas|lapack|r-base|r-matrix|r-lme4|rpy2)"
# packages in environment at /Users/turbach/miniconda3/envs/test_pymer4_3.8:
blas                      2.17                   openblas    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
liblapacke                3.8.0               17_openblas    conda-forge
libopenblas               0.3.10          openmp_h63d9170_3    conda-forge
pymer4                    0.7.1            py38r7e98fa2_0    ejolly
python                    3.8.5                h26836e1_1  
python-dateutil           2.8.1                      py_0  
python_abi                3.8                      1_cp38    conda-forge
r-base                    3.6.1                h8cbdff8_5    conda-forge
r-lme4                    1.1_21            r36h466af19_0  
r-matrix                  1.2_17            r36h46e59ec_0  
rpy2                      3.3.6           py38r36h174b24a_0    conda-forge
(test_pymer4_3.8) tpumbp3:pymer4 turbach$
```

The installer pulled  r-* packages from -c r as expected given the -c default -c conda-forge channel priority **except for r-base which is from conda-forge!**. Switching r-base from -c r to -c conda-forge when -c r has priority is unexpected and why it happens here with the explicit python version 3.8 and not with the default install which is also python 3.8 is a mystery to me.

Further, and perhaps related, instead of mkl blas it installed openblas. Switching to openblas unasked for is not a good thing for various reasons, starting with it breaks numpy. The numpy is installed from -c default where mkl is the norm and it doesn't play nice with the conda-forge openblas (though conda-forge numpy does).

Here's numpy's complaint in the freshly  built env

```
(base) tpumbp3:pymer4_test2 turbach$ conda activate test_pymer4_3.8
(test_pymer4_3.8) tpumbp3:pymer4_test2 turbach$ python -c "import numpy; numpy.show_config()"
Traceback (most recent call last):
  File "/Users/turbach/miniconda3/envs/test_pymer4_3.8/lib/python3.8/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/Users/turbach/miniconda3/envs/test_pymer4_3.8/lib/python3.8/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/Users/turbach/miniconda3/envs/test_pymer4_3.8/lib/python3.8/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dlopen(/Users/turbach/miniconda3/envs/test_pymer4_3.8/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so, 2): Library not loaded: @rpath/libopenblas.dylib
  Referenced from: /Users/turbach/miniconda3/envs/test_pymer4_3.8/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/turbach/miniconda3/envs/test_pymer4_3.8/lib/python3.8/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/Users/turbach/miniconda3/envs/test_pymer4_3.8/lib/python3.8/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "/Users/turbach/miniconda3/envs/test_pymer4_3.8/bin/python"
  * The NumPy version is: "1.19.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/Users/turbach/miniconda3/envs/test_pymer4_3.8/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so, 2): Library not loaded: @rpath/libopenblas.dylib
  Referenced from: /Users/turbach/miniconda3/envs/test_pymer4_3.8/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so
  Reason: image not found

```

It is surprising to see the solver switch channels for r-base like that and then build an inconsistent environment without warning ... I suspect a defect in the installer. I don't know whether the conda-forge openblas is the chicken or the egg here ... if openblas has priority over mkl (why now?) that may trigger pulling r-base from conda-forge. Or maybe some R dependency requires openblas and that starts the cascade. With any luck I will never learn the answer.

For grins I reverted the conda back to version 4.8.5 and re-ran the same explicit python 3.8 install with no problems at all. The blas was mkl, the r-base and r-* packages installed from -c r as expected and pytests ran. So there is something different and likely wrong in conda 4.9.1.

As you say, one workaround is to switch over to conda-forge channel priority. This is a radical change b.c. it switches R algebra libraries to openblas instead of mkl. This is 50 - 100% performance hit on our 48 core intel server, reasons unknown and frankly uninteresting. Negotiating algebra libraries on -c default and -c conda-forge is a longstanding issue in conda land [How to stop the numpy openblas/mkl dance #108](https://github.com/conda-forge/numpy-feedstock/issues/108). As for what horse to back in the long run ... numpy+mkl or numpy+openblas ... dunno. As for right now, numpy+mkl (on the fragility and prospects of openblas [see here in their own words](https://labs.quansight.org/blog/2019/11/numpy-openblas-CZI-grant/))

Another workaround that is closer to the current default behavior is to insist that r-base come from the r channel during installation with the `channel::pkg` syntax like this:

`conda create -n test_force_r_pymer4 -c ejolly -c defaults -c conda-forge python=3.8 "r::r-base" pymer4`

Really shouldn't be necessary, but is an option until the root problem is fixed. 

```
(base) tpumbp3:~ turbach$ conda create -n test_force_r_pymer4 -c ejolly -c defaults -c conda-forge python=3.8 "r::r-base" pymer4
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/turbach/miniconda3/envs/test_force_r_pymer4

  added / updated specs:
    - pymer4
    - python=3.8
    - r::r-base

(test_force_r_pymer4) tpumbp3:pymer4_test2 turbach$ pytest
========================================================== test session starts ===========================================================
platform darwin -- Python 3.8.2, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: /Users/turbach/Work/testing/pymer4_test2
collected 31 items                                                                                                                       

pymer4/test_install.py .                                                                                                           [  3%]
pymer4/tests/test_models.py .......................                                                                                [ 77%]
pymer4/tests/test_simulate.py ..                                                                                                   [ 83%]
pymer4/tests/test_stats.py ....                                                                                                    [ 96%]
pymer4/tests/test_utils.py .                                                                                                       [100%]

============================================================ warnings summary ============================================================
../../../miniconda3/envs/test_force_r_pymer4/lib/python3.8/site-packages/patsy/constraint.py:13
  /Users/turbach/miniconda3/envs/test_force_r_pymer4/lib/python3.8/site-packages/patsy/constraint.py:13: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    from collections import Mapping

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=============================================== 31 passed, 1 warning in 123.79s (0:02:03) ================================================

```

As for why the conda install fails one way for me and another for you I can't guess without more specifics:

* for starters it would be useful to `conda list` the key packages in your environments that do and don't work to show what package binaries are actually installed from what channels.
* is your conda from -c main or -c conda-forge and what does `conda --version` show?
* is the conda install running in bash or zsh?
* any  stray R environment variables left over from the good old days of CRAN and install.packages  ... RPATH and friends?

**Comment by ejolly** [comment]
@turbach Realizing I never replied to this, but having just experienced the same issue again it seems like the only solution that reliably works for me on several different versions of mac OS, irrespective of conda version or python version (works on both 4.8.5 and 4.9.2, and 3.7, 3.8, 3.9) is to  
 __force conda to install `r-base` from the `r` channel rather than `conda-forge`__, as you suggested:

`conda create --name pymer4 -c ejolly -c defaults -c conda-forge python=3.8 "r::r-base" pymer4`

For whatever reason, even after downgrading `conda` 4.9.2 -> 4.8.X, the solver still tries to pull `r-base` from `conda-forge`, plus it tries to pull lots of other r libraries from `conda-forge` as well and grabs blas instead of mkl. 

### r-base from conda-forge + blas (numpy and pymer4 broken)

Running `conda create --name pymerblas -c ejolly -c defaults -c conda-forge pymer4` on 4.8 or 4.9 yield the following specs:

```
## Package Plan ##

  environment location: /Users/Esh/anaconda3/envs/pymerblas

  added / updated specs:
    - pymer4


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    blas-2.3                   |         openblas          11 KB  conda-forge
    c-ares-1.17.1              |       h9ed2024_0          92 KB
    cairo-1.16.0               |    he8db5a5_1006         1.3 MB  conda-forge
    cctools_osx-64-949.0.1     |      h8e49ea9_16         1.8 MB  conda-forge
    cffi-1.14.4                |   py38h2125817_0         217 KB
    clang-11.0.0               |       h694c41f_2         124 KB  conda-forge
    clang-11-11.0.0            |default_h9e6edd0_2         675 KB  conda-forge
    clang_osx-64-11.0.0        |       hb91bd55_8          15 KB  conda-forge
    clangxx-11.0.0             |default_h9e6edd0_2         124 KB  conda-forge
    clangxx_osx-64-11.0.0      |       h7e1b574_8          15 KB  conda-forge
    compiler-rt-11.0.0         |       h01488ec_2          78 KB  conda-forge
    compiler-rt_osx-64-11.0.0  |       hd3c4e95_2         5.6 MB  conda-forge
    curl-7.71.1                |       hcb81553_8         131 KB  conda-forge
    fontconfig-2.13.1          |    h186bf41_1002         269 KB  conda-forge
    gfortran_impl_osx-64-9.3.0 |      h7d6baa2_13        11.3 MB  conda-forge
    gfortran_osx-64-9.3.0      |      h2de5253_10          21 KB  conda-forge
    gmp-6.2.1                  |       h2e338ed_0         774 KB  conda-forge
    gsl-2.6                    |       hdac7af7_0         3.0 MB  conda-forge
    harfbuzz-2.7.2             |       h73e2de6_1         1.6 MB  conda-forge
    hdf5-1.10.6                |nompi_h0f9794f_1112         3.0 MB  conda-forge
    icu-67.1                   |       hb1e8313_0        12.6 MB  conda-forge
    isl-0.22.1                 |       hb1e8313_2         790 KB  conda-forge
    jpeg-9d                    |       hbcb3906_0         250 KB  conda-forge
    krb5-1.17.1                |       hddcf347_0         1.1 MB
    ld64_osx-64-530            |      h66d9e41_16         1.3 MB  conda-forge
    ldid-2.1.2                 |       h7660a38_2          55 KB  conda-forge
    libblas-3.9.0              |       3_openblas          11 KB  conda-forge
    libcblas-3.9.0             |       3_openblas          11 KB  conda-forge
    libclang-cpp11-11.0.0      |default_h9e6edd0_2        12.5 MB  conda-forge
    libcurl-7.71.1             |       h9bf37e3_8         297 KB  conda-forge
    libcxx-11.0.0              |       h4c3b8ed_1         1.0 MB  conda-forge
    libev-4.33                 |       haf1e3a3_0         106 KB
    libgfortran-5.0.0          |      h7cc5361_13          18 KB  conda-forge
    libgfortran-devel_osx-64-9.3.0|      h7cc5361_13         246 KB  conda-forge
    libgfortran5-9.3.0         |      h7cc5361_13         1.7 MB  conda-forge
    libglib-2.66.3             |       h60154bc_1         2.8 MB  conda-forge
    liblapack-3.9.0            |       3_openblas          11 KB  conda-forge
    liblapacke-3.9.0           |       3_openblas          11 KB  conda-forge
    libllvm11-11.0.0           |       hf85e3d2_0        22.5 MB  conda-forge
    libnghttp2-1.41.0          |       h7580e61_2         665 KB
    libopenblas-0.3.12         |openmp_h54245bb_1         8.8 MB  conda-forge
    libxml2-2.9.10             |       h2c6e4a5_2         1.2 MB  conda-forge
    llvm-openmp-11.0.0         |       h73239a0_1         268 KB  conda-forge
    llvm-tools-11.0.0          |       hf85e3d2_0        11.7 MB  conda-forge
    numexpr-2.7.1              |   py38h9ff8ad3_0         120 KB
    numpy-1.19.2               |   py38h63973fd_0          21 KB
    numpy-base-1.19.2          |   py38h68fea81_0         4.1 MB
    pango-1.42.4               |       ha86e081_5         526 KB  conda-forge
    pytables-3.6.1             |   py38h4e4ac5c_3         1.4 MB  conda-forge
    r-base-3.6.3               |       h280a0cc_4        22.9 MB  conda-forge
    r-minqa-1.2.4              | r36ha6353f9_1006         138 KB  conda-forge
    r-mvtnorm-1.1_1            |    r36h43cf36c_1         240 KB  conda-forge
    r-nlme-3.1_150             |    r36h43cf36c_0         2.3 MB  conda-forge
    r-nloptr-1.2.2.2           |    r36hc5da6b9_0         536 KB  conda-forge
    scipy-1.5.3                |   py38hb6cd474_0        17.0 MB  conda-forge
    tapi-1100.0.11             |       h9ce4665_0         196 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       159.4 MB
```

### r-base from defaults + mkl (numpy and pymer4 work)

Running `conda create --name pymermkl -c ejolly -c defaults -c conda-forge "r::r-base" pymer4` on 4.8 or 4.9 yield the following specs (and fails the initial solve):

```
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/Esh/anaconda3/envs/pymermkl

  added / updated specs:
    - pymer4
    - r::r-base


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _r-mutex-1.0.0             |      anacondar_1           3 KB
    blas-1.0                   |              mkl           6 KB
    bwidget-1.9.11             |                1         115 KB
    cairo-1.14.12              |       hc4e6be7_4         860 KB
    cctools-927.0.2            |       h5ba7a2e_4         965 KB
    cffi-1.14.0                |   py38hb5b8e2f_0         216 KB
    clang-10.0.0               |default_hf57f61e_0        10.0 MB
    clang_osx-64-10.0.0        |       h05bbb7f_0          15 KB
    clangxx-10.0.0             |default_hf57f61e_0         123 KB
    clangxx_osx-64-10.0.0      |       h05bbb7f_1          22 KB
    compiler-rt-10.0.0         |       h47ead80_0          82 KB
    compiler-rt_osx-64-10.0.0  |       hbcc88fd_0         1.4 MB
    curl-7.67.0                |       ha441bb4_0         125 KB
    deepdish-0.3.6             |     pyh9f0ad1d_0          34 KB  conda-forge
    fontconfig-2.13.0          |       h5d5b041_1         202 KB
    fribidi-1.0.10             |       haf1e3a3_0          63 KB
    gettext-0.19.8.1           |       h15daf44_3         2.6 MB
    gfortran_osx-64-4.8.5      |       h22b1bf0_8         6.1 MB
    glib-2.63.1                |       hd977a24_0         2.6 MB
    graphite2-1.3.14           |       h38d11af_0          80 KB
    gsl-2.4                    |       h1de35cc_4         1.8 MB
    harfbuzz-2.4.0             |       h831d699_0         608 KB
    krb5-1.16.4                |       hddcf347_0        1021 KB
    ld64-450.3                 |       h3c32e8a_4         858 KB
    libcurl-7.67.0             |       h051b688_0         377 KB
    libffi-3.2.1               |    h0a44026_1007          43 KB
    libllvm10-10.0.1           |       h76017ad_5        16.4 MB
    make-4.2.1                 |       h3efe00b_1         238 KB
    matplotlib-3.3.2           |                0          24 KB
    mkl-service-2.3.0          |   py38h9ed2024_0          41 KB
    numpy-1.19.2               |   py38h456fd55_0          21 KB
    pango-1.42.4               |       hc249df1_1         453 KB
    pip-20.3                   |   py38hecd8cb5_0         1.8 MB
    pixman-0.40.0              |       haf1e3a3_0         340 KB
    pymer4-0.7.1               |   py38r7e98fa2_0          80 KB  ejolly
    python-3.8.2               |       hfe9666f_0        20.8 MB
    python_abi-3.8             |           1_cp38           4 KB  conda-forge
    r-assertthat-0.2.1         |    r36h6115d3f_0          74 KB
    r-base-3.6.1               |       hcb44179_1        40.1 MB  r
    r-boot-1.3_20              |    r36h6115d3f_0         698 KB
    r-cli-1.1.0                |    r36h6115d3f_0         189 KB
    r-colorspace-1.4_1         |    r36h46e59ec_0         2.3 MB
    r-crayon-1.3.4             |    r36h6115d3f_0         757 KB
    r-dichromat-2.0_0          |    r36h6115d3f_4         163 KB
    r-digest-0.6.18            |    r36h46e59ec_0         141 KB
    r-emmeans-1.3.4            |    r36h6115d3f_0         1.1 MB
    r-estimability-1.3         |    r36h6115d3f_0          58 KB
    r-fansi-0.4.0              |    r36h46e59ec_0         173 KB
    r-ggplot2-3.1.1            |    r36h6115d3f_0         3.6 MB
    r-glue-1.3.1               |    r36h46e59ec_0         158 KB
    r-gtable-0.3.0             |    r36h6115d3f_0         425 KB
    r-labeling-0.3             |    r36h6115d3f_4          71 KB
    r-lattice-0.20_38          |    r36h46e59ec_0         1.1 MB
    r-lazyeval-0.2.2           |    r36h46e59ec_0         153 KB
    r-lme4-1.1_21              |    r36h466af19_0         4.7 MB
    r-lmertest-3.1_0           |    r36h6115d3f_0         454 KB
    r-magrittr-1.5             |    r36h6115d3f_4         173 KB
    r-mass-7.3_51.3            |    r36h46e59ec_0         1.1 MB
    r-matrix-1.2_17            |    r36h46e59ec_0         3.3 MB
    r-mgcv-1.8_28              |    r36h46e59ec_0         2.6 MB
    r-minqa-1.2.4              |    r36hbe7ee20_4         131 KB
    r-munsell-0.5.0            |    r36h6115d3f_0         254 KB
    r-mvtnorm-1.0_10           |    r36hfffe0aa_0         228 KB
    r-nlme-3.1_139             |    r36hfffe0aa_0         2.2 MB
    r-nloptr-1.2.1             |    r36hbe7ee20_0         442 KB
    r-numderiv-2016.8_1        |    r36h6115d3f_0         132 KB
    r-pillar-1.3.1             |    r36h6115d3f_0         180 KB
    r-pkgconfig-2.0.2          |    r36h6115d3f_0          25 KB
    r-plyr-1.8.4               |    r36h466af19_0         787 KB
    r-r6-2.4.0                 |    r36h6115d3f_0          68 KB
    r-rcolorbrewer-1.1_2       |    r36h6115d3f_0          62 KB
    r-rcpp-1.0.1               |    r36h466af19_0         3.2 MB
    r-rcppeigen-0.3.3.5.0      |    r36h466af19_0         1.4 MB
    r-reshape2-1.4.3           |    r36h466af19_0         109 KB
    r-rlang-0.3.4              |    r36h46e59ec_0         985 KB
    r-scales-1.0.0             |    r36h466af19_0         546 KB
    r-stringi-1.4.3            |    r36h466af19_0         692 KB
    r-stringr-1.4.0            |    r36h6115d3f_0         221 KB
    r-tibble-2.1.1             |    r36h46e59ec_0         302 KB
    r-utf8-1.1.4               |    r36h46e59ec_0         133 KB
    r-viridislite-0.3.0        |    r36h6115d3f_0          66 KB
    r-withr-2.1.2              |    r36h6115d3f_0         181 KB
    r-xtable-1.8_4             |    r36h6115d3f_0         717 KB
    readline-7.0               |       h1de35cc_5         316 KB
    rpy2-3.3.6                 |py38r36hfb243c8_0         358 KB  conda-forge
    tapi-1000.10.8             |       ha1b3eb9_0         4.2 MB
    tktable-2.10               |       h1de35cc_0          75 KB
    tzlocal-2.1                |           py38_0          29 KB
    ------------------------------------------------------------
                                           Total:       151.8 MB
```

To further complicate matters, if you have at least one environment with pymer installed (with r-base from r), then any other environments will properly resolve numpy and r packages without the need to specify (I'm assuming because conda tries to re-use some packages across environments). However, if there are no working environments with pymer4 then you need to be specific about where r-base comes from.
